### ISSUE TITLE
Build Select dynamically

### ISSUE THREAD

**Issue by Phil-Barber** [mitsuhiko/dialoguer#108]
Looking to build a Select that only displays 3 at a time. I think this would be a useful feature that I'd be happy to add if others would find it useful.

However I'm running into compiler issues.  I'm a beginner so apologies if I'm missing something obvious:
```
fn three_at_a_time() -> Result<()> {
    let mut results_iter = vec![1,2,3,4,5].iter();

    let items_per_page = 3;
    let mut selector = Select::new();
    for _ in 1..=items_per_page {
        let next = results_iter.next();
        if next.is_none() {
            selector = selector.item(next.unwrap());
        }
    }
    let _chosen = selector.interact()?;
    
    Ok(())
}
```
Error:
```
error[E0308]: mismatched types
  --> src/main.rs:44:24
   |
44 |             selector = selector.item(next.unwrap())
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Select`, found `&mut Select<'_>`
```

**Comment by SirWindfield** [comment]
`Select::item` takes `&mut self`, a mutable reference to a select instance. You specify Select as mutable, but call it as `selector = selector.item(...)`. First off, no need to re-set the selector, as it returns a mutable reference to the same struct. It's basically the same as `selector.item(...);`. 
Secondly, I think it would compile if you call `&selector.item(...)` only. The error  occurs because you assign the return type of item, which is a mutable reference, to a variable of type `mut Select`.

**Comment by Phil-Barber** [comment]
Thank you! I really thought I had attempted that, apologies. 
Both `selector.item(...);` and `&selector.item(...);` work as desired 👍

**Comment by SirWindfield** [comment]
Ah ye, true, the first one works as well, I forgot! Glad I could help :)
