### ISSUE TITLE
Fuzzy Select doesn't color currently selected item

### ISSUE THREAD

**Issue by Araxeus** [mitsuhiko/dialoguer#195]
I think match highlighting in https://github.com/mitsuhiko/dialoguer/pull/179 caused an undocumented feature regression/bug?

Fuzzy Select doesn't color the currently selected item

in `v0.10.0` currently selected item was highlighted in blue (using `ColorfulTheme`)
but now in `v0.10.1` it isn't anymore...

It's important to note that it doesn't work regardless of if `.highlight_matches()` is `false` or `true` 

(since `.highlight_matches(false)` should behave exactly like in `v0.10.0`, I think this is a bug)

----
On a side note:

I set the highlight style to be Bold only using:
```rust
let theme = ColorfulTheme {
    fuzzy_match_highlight_style: console::Style::new().for_stderr().bold(),
    ..Default::default()
};
```

I think this looks better, so maybe `bold` should be the default instead of `yellow`+`bold`
(especially since the yellow color clash with the currently selected blue color that hopefully will be back)

----

**Comment by deg0nz** [comment]
You are absolutely right, this is a bug. I forgot to apply the style to the selected item.

> I think this looks better, so maybe bold should be the default instead of `yellow`+`bold`

I intentionally chose `yellow`+`bold` because `bold` only was not enough contrast imho.

I tried different variants and I'm not really happy with any of them. Maybe the community can decide what they like best.
Here are they:

1. Active item coloured and highlighted chars in active item bold:

![fuzzy-select-highlight-bold](https://user-images.githubusercontent.com/6370295/167501795-d651bc5e-0ea7-41de-a50a-2b133c09a266.gif)

2. Active item coloured and highlighted chars bold+yellow:

![fuzzy-select-highlight-bold-color](https://user-images.githubusercontent.com/6370295/167502228-c14a90db-79f9-4440-bdd5-9ce0323abb83.gif)

3. Active item coloured with highlighted chars bold only everywhere:

![fuzzy-select-highlight-bold-all](https://user-images.githubusercontent.com/6370295/167502520-c5810dff-678d-4a20-ad55-54247b978430.gif)

I personally like no 1 best, tbh. 
No2 is somewhat of colour-clashy, as @Araxeus correctly mentioned.
No3 has not enough contrast.

**Comment by Araxeus** [comment]
I personally like N3 best, I think the char highlight should be mellow and not super noticeable
(which is how it looks in vscode and how it was suggested in #163)

No1 is weird because the char highlight seems to disappear
(yes it becomes bold, but you don't expect it to be since all others are yellow)

No2 is color clashy indeed and shouldn't ever be a default

Anyways I think there should be some documentation about customizing this style, like the example I wrote above^
(best would be to make `.highlight_matches()` receive either a bool or `console::Style` but not sure how that would work)

**Comment by Araxeus** [comment]
@deg0nz could you open a PR that will fix the bug since you seem to have coded the fix already?

**Comment by Araxeus** [comment]
If you think Bold isn't visible enough, `console::Style::new().for_stderr().bold().italic()` looks quite good imo

**Comment by deg0nz** [comment]
I decided to go for the bold only option. I think this is more of what initially was requested in #163. 
The lack of contrast in my examples could come from the font use in my terminal and it's weight.
