### ISSUE TITLE
Match input and validator generic type

### ISSUE THREAD

**Issue by vallentin** [mitsuhiko/dialoguer#43]
Assuming #42 gets merged, then we can always guarantee that the input value is of type `T` instead of using `&str`. So I have a request of changing the validator to receive `&T` instead of `&str`.

**Examples:**

As in, this:

```rust
Input::<i32>::new()
    .validate_with(|input: &i32| -> Result<(), &str> {
        todo!()
    });

Input::<char>::new()
    .validate_with(|input: &char| -> Result<(), &str> {
        todo!()
    });
```

Instead of:

```rust
Input::<i32>::new()
    .validate_with(|input: &str| -> Result<(), &str> {
        todo!()
    });

Input::<char>::new()
    .validate_with(|input: &str| -> Result<(), &str> {
        todo!()
    });
```

*Note `&i32` and `&char` vs `&str`  and`&str`.*

**Comment by jamesmcm** [comment]
Nice work, this is a breaking change though and really confused me when trying to check some things on the current codebase vs. the crates.io version.

Please could you release this to crates.io and bump the version?

**Comment by pksunkara** [comment]
I am planning a few more breaking changes before I do. Will try to do it soon.

**Comment by jamesmcm** [comment]
Thanks, I'm creating a PR now to remove the `'static` restriction on the validate_with closure as it is unnecessary (since we should be able to pass outside values in to the closure which live longer than the Input but are not static).

But the pain at the moment is that since for the `Input<T>`, T is the owned type i.e. String, then the closure must accept &String and cannot accept &str. I tried to work around this with `AsRef` but it won't work unless we change the T to be the base type i.e. &str and then use ToOwned to make it return the owned type (we could even use Cow).

But that's a big change that means all existing code using Input<T> would need to change :crying_cat_face:
