### ISSUE TITLE
Confirmation should wait for Enter key to be pressed

### ISSUE THREAD

**Issue by abonander** [mitsuhiko/dialoguer#66]
Currently the confirmation proceeds immediately on a single key being input, which isn't really inline with conventional CLI design. I'd expect it to wait for Enter to be pressed even when giving an explicit answer.

**Comment by pksunkara** [comment]
This should be optional behaviour user can opt in to.

**Comment by abonander** [comment]
Every CLI program I've ever used that's implemented confirmations like this has waited for the Enter key, so I would argue that it should be the default, but if the alternative is not having it at all then I'm fine with it being optional.

**Comment by nicklasring** [comment]
Just noticed this, should really wait for the user to press enter so you have one extra second to think over what you're doing or as @pksunkara wrote, an optional behaviour.

**Comment by abreis** [comment]
I've opened a PR in #70. 

I opted to keep the current behavior as the default since apps using `Confirm` could be part of scripts (e.g., via `expect`) and this change in behavior would break them, but I agree that this new behavior feels more unix-y and should be made the default in a future release.
